---

- name: Everywhere
  become: yes
  hosts: all
  roles:
    - common
    - sudoers
    - iptables

- name: Application servers
  become: yes
  hosts: apps
  roles:
    - access
    - nginx-proxy
    - mod_php
    - vsftpd
    - postfix

- name: DB servers
  become: yes
  hosts: databases
  roles:
    - mariadb
    - redis
