- name: iptables-load
  shell: iptables-restore < /etc/sysconfig/iptables

- name: iptables-started
  service:
    name=iptables
    state=started

- name: iptables-restarted
  service:
    name=iptables
    state=restarted

- name: iptables-stopped
  service:
    name=iptables
    state=stopped

