- name: installing packages
  yum:
    pkg={{ item }}
    state=latest
  notify:
    - httpd-enabled
  with_items: "{{ httpd_packages }}"
  tags:
    - httpd

- name: creating extra folder
  file:
    path=/etc/httpd/{{ item }}
    state=directory
  with_items:
    - conf/extra
  tags:
    - httpd

- name: copying configs
  template:
    src=etc/httpd/{{ item }}.j2
    dest=/etc/httpd/{{ item }}
  with_items:
    - conf/httpd.conf
    - conf/extra/icons.conf
    - conf/extra/language.conf
    - conf/extra/logging.conf
    - conf/extra/modules.conf
    - conf/extra/mpm.conf
    - conf/extra/random.conf
    - conf/extra/vhosts.conf
  notify:
    - httpd-restarted
  when: ansible_distribution_major_version == "6"
  tags:
    - httpd

- name: copying virtual hosts
  template:
    src=etc/httpd/conf.d/default.conf.j2
    dest=/etc/httpd/conf.d/{{ item.key }}.conf
  notify:
    - httpd-restarted
  with_dict: "{{ projects }}"
  tags:
    - httpd

- name: creating directories for logging
  file:
    path={{ "%s/%s"|format(httpd_logdir, item.key) }}
    mode=0755
    owner=apache
    group=root
    state=directory
    recurse=yes
  with_dict: "{{ projects }}"
  tags:
    - httpd
