language: bash
dist: trusty

cache: apt

before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible python-dev
  - sudo apt-get remove -y python-openssl
  - sudo pip install -U pip
  - sudo pip install pyopenssl
  - sudo pip install ansible-lint

script:
  - bash tests/ansible-validate
