language: bash

cache: apt

before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible ansible-lint

script:
  - bash tests/ansible-validate
