---

- name: checking for installed
  yum:
    name={{ item }}
    state=installed
  register: lego_is_installed
  with_items: lego_packages
  tags:
    - ssl

- name: installing latest version
  yum:
    name={{ item }}
    state=latest
  with_items: lego_packages
  tags:
    - ssl

- name: signing certificates
  shell: yes | lego --email {{ item.value.email|default('webmaster@' + item.key) }} \
    --rsa-key-size 2048 \
    --path "{{ lego_path }}" \
    --domains="{{ item.key }}" \
    {{ item.value.aliases|format_list('--domains=%s ') }} run
  with_dict: projects
  when: lego_is_installed|changed
  tags:
    - ssl
