- name: loading upstreams
  template:
    src=etc/nginx/conf.d/upstream.conf.j2
    dest=/etc/nginx/conf.d/upstream.conf
  tags:
    - nginx

- name: loading virtual hosts
  template:
    src=etc/nginx/conf.d/default.conf.j2
    dest=/etc/nginx/conf.d/{{ item.key }}.conf
  notify:
    - nginx-restarted
  with_dict: "{{ projects }}"
  tags:
    - nginx
